import { createMessage, storeMessage } from "./utils.js";
import { initializeApp } from "./app.js";
import { auth } from "./firebase.js";

/* I have taken the Google form the Solon team was using and used this tool: https://stefano.brilli.me/google-forms-html-exporter/
to extract the form elements and  code to submit the form. The input names are generated by Google and can not be changed */
const mailingListForm = document.getElementById(
  "mailingList",
) as HTMLFormElement;

function submitData() {
  //Create submitting data message
  createMessage("Submitting contact data...", "main-message", "info");
  const mailingFormData: FormData = new FormData(mailingListForm);

  //Validate full name input
  const fullNameValue = mailingFormData.get("entry.961884440");
  if (fullNameValue === null || fullNameValue.toString().trim() === "") {
    createMessage("Please enter your name", "main-message", "error");
    return;
  } else {
    const firstLastCheck = fullNameValue.toString().split(" ");
    if (firstLastCheck.length < 2) {
      createMessage(
        "Please enter your first and last name",
        "main-message",
        "error",
      );
      return;
    }
  }
  //Validate email
  const emailValue = mailingFormData.get("entry.1887592473");
  if (emailValue === null || emailValue.toString().trim() === "") {
    createMessage("Please enter your email", "main-message", "error");
    return;
  }
  const checkForAtSymbol = emailValue.toString().split("@");
  if (checkForAtSymbol.length < 2) {
    createMessage("Please enter a valid email", "main-message", "error");
    return;
  }
  //Validate phone if entered
  const phoneValue = mailingFormData.get("entry.536914204");
  if (phoneValue !== null && phoneValue.toString().replace(/\D/g, "") !== "") {
    const parsedPhone: number = parseInt(
      phoneValue.toString().replace(/\D/g, ""),
    );
    if (isNaN(parsedPhone)) {
      createMessage(
        "Please enter a valid phone number",
        "main-message",
        "error",
      );
      return;
    } else {
      const lengthCheck: number = String(Math.abs(parsedPhone)).length;
      if (lengthCheck < 10 || lengthCheck > 11) {
        createMessage(
          "Please enter a valid phone number",
          "main-message",
          "error",
        );
        return;
      }
    }
  }
  //Validate volunteer type
  const volunteerTypeValue = mailingFormData.get("entry.1214187848");
  if (volunteerTypeValue === null) {
    createMessage(
      "Please select what kind of emails you would like to receive",
      "main-message",
      "error",
    );
    return;
  }
  //If there are no errors, send the form data to the form response spreadsheet.
  const formData: FormData = new FormData(mailingListForm);
  const formAction: string =
    "https://docs.google.com/forms/d/e/1FAIpQLSeI082sAdNAfYFnAbLUfuL3dqpz8B7CPKZfxCI_MlT9x-cmAg/formResponse";
  fetch(formAction, {
    method: "POST",
    body: formData,
    mode: "no-cors",
  })
    .then((response) => {
      //Store the message to be displayed after redirected to the home page
      storeMessage(
        "You have been signed up for our mailing list",
        "main-message",
        "check_circle",
      );
      window.location.href = "index.html";
    })
    .catch((error) => {
      //Create an error message
      console.error("Network Error:", error);
      createMessage(
        "Error. Please try reloading the page",
        "main-message",
        "error",
      );
    });
}

initializeApp("Mailing List", "Mailing List").then(() => {
  //If the user is signed in, populate the input fields with the user's info
  auth.onAuthStateChanged((user) => {
    if (user) {
      const fullNameInput = document.getElementById(
        "fullNameInput",
      ) as HTMLFormElement;
      fullNameInput.value = user.displayName;
      const emailInput = document.getElementById(
        "emailInput",
      ) as HTMLFormElement;
      emailInput.value = user.email;
      //Not populating phoneNumberInput since the field is optional
    }
  });
});

mailingListForm.addEventListener("submit", (e) => {
  e.preventDefault();
  submitData();
});
